version: 0.0
os: linux
files:
  - source: /dds-ui.war
    destination: /opt/tomcat/webapps
  - source: /eds-api.war
    destination: /opt/tomcat/webapps
hooks:
  BeforeInstall:
    - location: cleanup
      timeout: 300
      runas: root
